 Perform a numerical analysis and data manipulation using the numpy library

1. Create a numpy array

In [3]:
import numpy as np
arr1 = np.array([1,2,3])
print (arr1)

[1 2 3]


2. Access and Manipulate elements in he array 

In [4]:
arr1[2]

3

In [5]:
arr1[2] =5
arr1

array([1, 2, 5])

3. Create a 2-Dimensional array and check the shape of te array

In [6]:
arr2 =np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [7]:
print("The shape is 2 rows and 3 columns:",arr2.shape)

The shape is 2 rows and 3 columns: (2, 3)


4. Access elements from the 2D array using index positions 

In [8]:
print(arr2[0][2])
print(arr2[0,2])
print(arr2[0,-1])
print(arr2[-1,0])

3
3
3
4


In [9]:
arr3 =np.array(['India','china','USA','Mexico'])
print(arr3)


['India' 'china' 'USA' 'Mexico']


In [10]:
arr3[1]

'china'

6. Using the array () and liespace() function to evenly space values in a specified interval

In [15]:
arr = np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [17]:
arr=np.linspace(0,10,20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


7. Create an array of random values between 0and 1 in a given shape

In [18]:
arr = np.random.rand(10)
print(arr)
print('\n')
arr=np.random.rand(3,4)
print(arr)

[0.50248209 0.67278614 0.5355581  0.27052853 0.43173904 0.33663674
 0.85735533 0.52209046 0.31054863 0.84119649]


[[0.95163668 0.17283862 0.72052364 0.23092091]
 [0.84068169 0.68543077 0.37507663 0.46025265]
 [0.49588948 0.33597006 0.66408316 0.84669103]]


8.create an array of constant values in a given shape 

In [20]:
print(np.full((4,6),10))

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


9.Repeat each element of an array by a specified number times using repeat()and tile() functions 

In [21]:
arr= [0,1,2]
print(np.repeat(arr,3))

[0 0 0 1 1 1 2 2 2]


In [22]:
arr= [0,1,2]
print(np.tile(arr,3))

[0 1 2 0 1 2 0 1 2]


10.Create an identity matrix using eye() and identity() function 

In [23]:
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
identity_matrix=np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


11. Create a 5x5 2D arrray for random numbers between 0 and 1

In [28]:
arr=np.random.rand(5,5)
print(arr)

[[0.75504698 0.53582752 0.76587403 0.08435889 0.72234526]
 [0.27727116 0.67236821 0.93518705 0.36238046 0.31455474]
 [0.65113488 0.96004658 0.78232773 0.02952986 0.84890395]
 [0.77103934 0.54480224 0.27272773 0.41274568 0.42955953]
 [0.14074765 0.814866   0.46137664 0.54340545 0.91842014]]


12. Sum and array long the column

In [29]:
print(np.sum(arr,axis=0))

[2.59524001 3.52791055 3.21749317 1.43242034 3.23378362]


14.Sum and array long the row

In [30]:
print(np.sum(arr,axis=1))

[2.86345268 2.56176161 3.271943   2.43087452 2.87881587]


14. Calculate the mean, median , standard deviatin ad varience

In [31]:
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

0.5602739074401145
0.5448022379676273
0.26788429380753426
0.07176199486876135


15.Sort an array along the row using the sot() fuction

In [33]:
arr=np.random.rand(5,5)
print(arr)

[[0.96250511 0.44991813 0.86795319 0.64370037 0.74446333]
 [0.9093703  0.23965064 0.71906436 0.55915094 0.61991323]
 [0.51325789 0.99156963 0.55061058 0.46291991 0.29701399]
 [0.45832151 0.2788991  0.07755559 0.12531788 0.55512687]
 [0.25292797 0.77049227 0.44338794 0.12672865 0.43216753]]


In [34]:
print(np.sort(arr,axis=1))

[[0.44991813 0.64370037 0.74446333 0.86795319 0.96250511]
 [0.23965064 0.55915094 0.61991323 0.71906436 0.9093703 ]
 [0.29701399 0.46291991 0.51325789 0.55061058 0.99156963]
 [0.07755559 0.12531788 0.2788991  0.45832151 0.55512687]
 [0.12672865 0.25292797 0.43216753 0.44338794 0.77049227]]


16. Append elements to an array using the append() function

In [35]:
arr=np.array([4,5,6])
arr1=np.append(arr,8)
arr1

array([4, 5, 6, 8])

In [36]:
arr2=np.append(arr,[9,10,11])
print(arr2)

[ 4  5  6  9 10 11]


17. Delete multiple elements in an array

In [37]:
arr2=np.array([4,5,6,7,9,10,11])
print(arr2)
print('\n')
arr5=np.delete(arr2,[1,4])
print(arr5)

[ 4  5  6  7  9 10 11]


[ 4  6  7 10 11]


18.Concatenate elements from 2 arrays

In [39]:
arr1=np.array([[1,2,3,4],[1,2,3,4]])
arr2=np.array([[5,6,7,8],[5,6,7,8]])

In [41]:
cat=np.concatenate((arr1,arr2),axis=0)
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [42]:
cat=np.concatenate((arr1,arr2),axis=1)
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
